# Generated by Django 5.2.14 on 2026-05-10 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location_address', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField()),
                ('current_location_lng', models.FloatField()),
                ('pickup_location_address', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField()),
                ('pickup_location_lng', models.FloatField()),
                ('dropoff_location_address', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField()),
                ('dropoff_location_lng', models.FloatField()),
                ('current_cycle_used', models.FloatField()),
                ('total_distance_miles', models.FloatField(null=True)),
                ('total_duration_hours', models.FloatField(null=True)),
                ('fuel_cost_estimate', models.FloatField(null=True)),
                ('route_geometry', models.JSONField(null=True)),
                ('stops', models.JSONField(null=True)),
                ('driving_segments', models.JSONField(null=True)),
                ('daily_logs', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
